version: "3.7"
services:
 db:
  image: mariadb:10.4.8
  container_name: dj-mariadb
  restart: always
  environment:
   - MYSQL_ROOT_PASSWORD=rootpw
   - MYSQL_USER=domjudge
   - MYSQL_PASSWORD=djpw
   - MYSQL_DATABASE=domjudge
  ports:
   - 13306:3306
 domserver:
  image: domjudge/domserver:latest
  container_name: domserver
  restart: always
  environment:
   - MYSQL_HOST=dj-mariadb
   - MYSQL_USER=domjudge
   - MYSQL_DATABASE=domjudge
   - MYSQL_PASSWORD=djpw
   - MYSQL_ROOT_PASSWORD=rootpw
  ports:
   - 12345:80
 judgehost:
  image: domjudge/judgehost:latest
  container_name: judgehost-0
  volumes:
   - /sys/fs/cgroup:/sys/fs/cgroup:ro
  hostname: judgedaemon-0
  environment:
   - DAEMON_ID=0
